### ISSUE TITLE
[TypeScript] Antlr 4.13.0 tool does not generate correct import statement for superClass

### ISSUE THREAD

**Issue by kaby76** [antlr/antlr4#4302]
Antlr 4.13.0. My typescript port for [fortran90](https://github.com/kaby76/grammars-v4/tree/79df97e9dff43f7afebd8c404a5f63db404b0f57/fortran/fortran90) does not compile. This is because the Antlr tool generates an import statement in Fortran90Lexer.ts with incorrect syntax:
```
// Generated from Fortran90Lexer.g4 by ANTLR 4.13.0
// noinspection ES6UnusedImports,JSUnusedGlobalSymbols,JSUnusedLocalSymbols
import {
	ATN,
	ATNDeserializer,
	CharStream,
	DecisionState, DFA,
	Lexer,
	LexerATNSimulator,
	RuleContext,
	PredictionContextCache,
	Token
} from "antlr4";
import Fortran90LexerBase from './Fortran90LexerBase';
...
```
This code cannot compile due to the incorrect syntax for the import statement of the base class.
```
$ make
bash build.sh
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

changed 19 packages, and audited 20 packages in 3s

found 0 vulnerabilities
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

added 11 packages, and audited 12 packages in 3s

3 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
Fortran90Lexer.ts:14:8 - error TS2613: Module '"C:/msys64/home/Kenne/issues/g4-3399/fortran/fortran90/Generated-TypeScript-0/Fortran90LexerBase"' has no default export. Did you mean to use 'import { Fortran90LexerBase } from "C:/msys64/home/Kenne/issues/g4-3399/fortran/fortran90/Generated-TypeScript-0/Fortran90LexerBase"' instead?

14 import Fortran90LexerBase from './Fortran90LexerBase';
          ~~~~~~~~~~~~~~~~~~

Fortran90Lexer.ts:472:8 - error TS2339: Property '_interp' does not exist on type 'Fortran90Lexer'.

472   this._interp = new LexerATNSimulator(this, Fortran90Lexer._ATN, Fortran90Lexer.DecisionsToDFA, new PredictionContextCache());
           ~~~~~~~

Fortran90Lexer.ts:472:40 - error TS2345: Argument of type 'this' is not assignable to parameter of type 'Recognizer<number>'.
  Type 'Fortran90Lexer' is missing the following properties from type 'Recognizer<number>': state, removeErrorListeners, addErrorListener

472   this._interp = new LexerATNSimulator(this, Fortran90Lexer._ATN, Fortran90Lexer.DecisionsToDFA, new PredictionContextCache());
                                           ~~~~

Fortran90Lexer.ts:498:16 - error TS2339: Property 'IsColumnZero' does not exist on type 'Fortran90Lexer'.

498    return this.IsColumnZero();
                   ~~~~~~~~~~~~

Test.ts:172:42 - error TS2345: Argument of type 'Fortran90Lexer' is not assignable to parameter of type 'Lexer'.
  Type 'Fortran90Lexer' is missing the following properties from type 'Lexer': _input, _interp, text, line, and 18 more.

172     const tokens = new CommonTokenStream(lexer);
                                             ~~~~~

Test.ts:174:11 - error TS2339: Property 'removeErrorListeners' does not exist on type 'Fortran90Lexer'.

174     lexer.removeErrorListeners();
              ~~~~~~~~~~~~~~~~~~~~

Test.ts:180:11 - error TS2339: Property 'addErrorListener' does not exist on type 'Fortran90Lexer'.

180     lexer.addErrorListener(listener_lexer);
              ~~~~~~~~~~~~~~~~

Test.ts:183:34 - error TS2339: Property 'nextToken' does not exist on type 'Fortran90Lexer'.

183             var ro_token = lexer.nextToken();
                                     ~~~~~~~~~


Found 8 errors in 2 files.

Errors  Files
     4  Fortran90Lexer.ts:14
     4  Test.ts:172
mingw32-make: *** [makefile:3: build] Error 2
```
The correct syntax for the import statement should be:
```
import { Fortran90LexerBase } from './Fortran90LexerBase';
```
Once I change the generated file Fortran90Lexer.ts to have the correct syntax, the code works perfectly fine.  I think it safe to assume that import for a parser superclass has a similar flaw.

This is a complete show-stopper.

Attached is the code that works. I hand-edited the build.sh to comment out the antlr4 tool invoke, and fixed the generated Fortran90Lexer.ts to have the correct syntax. If you need to reproduce, just edit the build.sh to call antlr4 and run.

[Generated-TypeScript-0.zip](https://github.com/antlr/antlr4/files/11647441/Generated-TypeScript-0.zip)

**Comment by ericvergnaud** [comment]
Mmmm.. thanks for this.
Looks like a use case not covered by unit tests.
The import syntax is correct, what isn't correct is the export of Fortran90LexerBase which should be a default export.
Not sure what broke this, does it work in 4.12.1 ?

**Comment by kaby76** [comment]
Yes, the solution is to change the declaration for Fortran90LexerBase as follows:
```
import {Lexer, Token, CharStream} from "antlr4";

export default class Fortran90LexerBase extends Lexer {
...
```
The code now works fine. The grammar now works for 8 targets.

**Comment by ericvergnaud** [comment]
I guess this deserves an updated example in our docs.

**Comment by kaby76** [comment]
> I guess this deserves an updated example in our docs.

That would be nice, but I'm going to keep working on these ports over in grammars-v4. Who knows, maybe there will be more things uncovered. Again, thanks again!
