### ISSUE TITLE
Issue with parser generation in 4.2.2

### ISSUE THREAD

**Issue by teverett** [antlr/antlr4#561]
Hello everyone.  With the 4.2.2 code generation for this grammar:

https://github.com/antlr/grammars-v4/tree/master/basic

I get these compilation errors.  I've verified that the generated code compiles fine with 4.2.1:

[ERROR] COMPILATION ERROR : 

[INFO] -------------------------------------------------------------

[ERROR] /Users/tom/projects/grammars-v4/basic/target/generated-sources/antlr4/com/khubla/antlr/jvmBasicParser.java:[1058,53] int cannot be dereferenced

[ERROR] /Users/tom/projects/grammars-v4/basic/target/generated-sources/antlr4/com/khubla/antlr/jvmBasicParser.java:[1190,53] int cannot be dereferenced

[ERROR] /Users/tom/projects/grammars-v4/basic/target/generated-sources/antlr4/com/khubla/antlr/jvmBasicParser.java:[4351,53] int cannot be dereferenced

[ERROR] /Users/tom/projects/grammars-v4/basic/target/generated-sources/antlr4/com/khubla/antlr/jvmBasicParser.java:[4617,53] int cannot be dereferenced

[INFO] 4
